config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'exercices', to: 'pages#exercices'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home;end
  def exercices;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/exercices.html.erb
<div class="m-5">

  <h3 class='mt-3'>Exercice 1 : Guitars sounds</h3>

  <div class="keys">
    <div data-key="65">
      <kbd>A</kbd>
      <span>Accoustic</span>
    </div>
    <div data-key="69">
      <kbd>E</kbd>
      <span>Electric</span>
    </div>
    <div data-key="83">
      <kbd>S</kbd>
      <span>Synthetic</span>
    </div>
  </div>

  <audio data-key="65" src="guitars/sounds/acoustic.wav"></audio>
  <audio data-key="69" src="guitars/sounds/electric.wav"></audio>
  <audio data-key="83" src="guitars/sounds/synthetic.wav"></audio>

  <script>
    function playSound(e) {
      const audio = document.querySelector(`audio[data-key="${e.keyCode}"]`);
      const key = document.querySelector(`div[data-key="${e.keyCode}"]`);
      if (!audio) return;

      key.classList.toggle('playing');
      if(audio.paused) {
        audio.play();
      } else {
        audio.pause();
      }
    }

    window.addEventListener('keydown', playSound);
  </script>


  <h3 class='mt-5'>Exercice 2 : Christmas gift List</h3>
  
  <div class="wrapper" style='visibility:hidden;'>
  <div class="gifts" ></div>
    <form class="add-items">
      <input type="text" name="item" placeholder="Name" required>
      <input type="submit" value="+ Add gift idea">
      <button id="clear-list">Clear List</button>
    </form>
  </div>

  <script>
    const clearList = document.querySelector('#clear-list');
    const addItems  = document.querySelector('.add-items');
    const itemsList = document.querySelector('.gifts');
    const inputText = document.querySelector('input[type="text"]');
    const storage   = window.localStorage;
    let   items     = JSON.parse(storage.getItem('myItems')) || []

     displayList();

    function itemHTML (name, checked, index) {
      const html = `
        <input type="checkbox" data-index="${index}" id="item${index}" ${checked ? 'checked' : ''}>
        <label for="item${index}">${name}</label>
      `;
      return html
    }

    function saveLocalStorage () {
      storage.setItem('myItems', JSON.stringify(items))
    }

    function handleSubmit (e) {
      e.preventDefault()
      const item = { name: inputText.value, checked: false };
      items.push(item);
      e.target.reset();
      saveLocalStorage();
      displayList();
    }

    function displayList () {
      const html = items.reduce((html, item, index) => {
        return html += itemHTML(item.name, item.checked, index)
      }, '')
      itemsList.innerHTML = html
    }

    function handleCheckbox (e) {
      if (!e.target.matches('input')) return
      const index = e.target.dataset.index
      items[index].checked = !items[index].checked
      saveLocalStorage();
    }

    function handleClearList () {
      items = [];
      saveLocalStorage();
      displayList()
    }

    addItems.addEventListener('submit', handleSubmit);
    itemsList.addEventListener('click', handleCheckbox);
    clearList.addEventListener('click', handleClearList);
  </script>
</div>

app/views/pages/home.html.erb
<div class="m-5">
  <%= link_to 'Vers les exercices', exercices_path %>
  <h3 class='mt-3'>Démo</h3>
  <%# controller / lifecycle %>
  <div data-controller="demo" class='mt-3' id='demo'></div>





  <%# shorthand action %>
  <%# <div data-controller="demo" class='mt-3'>
    <button data-action="click->demo#hello">Hello</button>
  </div> %>


  <%# multiple actions %>
  <%# <div data-controller="demo" class='mt-3'>
    <button data-action="click->demo#hello">hello</button>
    <input data-action="demo#hello focus->demo#hello"></input>
  </div> %>






  <%# target uniq %>
  <%# <div data-controller="demo" class='mt-3'>
    <button data-action="demo#hello">
      hello
    </button>
    <input data-demo-target="name" type="text">
    <span data-demo-target="output" class='ml-2'></span>
  </div> %>


  <%# target multiple %>
  <%# <div data-controller="demo" class='mt-3'>
    <button data-action="demo#hello">
      hello
    </button>
    <input data-demo-target="name" type="text">
    <span data-demo-target="output" class='ml-2'></span>
    <span data-demo-target="output" class='ml-2'></span>
    <span data-demo-target="output" class='ml-2'></span>
    <span data-demo-target="output" class='ml-2'></span>
  </div> %>









  <%# asynchronous loading html %>
  <%# <div data-controller="demo"
     data-demo-messages-value="/messages.html"
     data-demo-users-value="https://jsonplaceholder.typicode.com/users"
  >

     <button data-action='demo#load' class='mt-2'>Load messages</button>
     <div data-target='demo.messages'></div>
     <button data-action='demo#print' class='mt-2'>Print Users in console</button>
  </div> %>









  <%# CSS classes %>
  <%# <div data-controller="demo"
       data-demo-users-value="https://jsonplaceholder.typicode.com/users"
       data-demo-printed-class="printed"
  >
     <button data-action='demo#print' data-demo-target="button" class='mt-2'>Print Users in console</button>
  </div> %>









  <%# inheritance %>
  <%# <div data-controller="parent">
    <p data-parent-target="element" />
  </div>

  <div data-controller="demo">
    <p data-demo-target="element" />
  </div> %>
</div>